// <auto-generated>
// Ce fichier définit des constantes pour les codes articles dans l’application Servweb.
// Utiliser ces constantes évite la répétition de chaînes magiques dispersées dans le code.
// </auto-generated>

namespace MobileSLI.Expedition.Web.Domain.Constants;

/// <summary>
/// Codes articles suivis par l'application Expédition.
/// Ces valeurs sont utilisées dans les écrans, les brouillons SQLite et le lot envoyé à l'API centrale.
/// </summary>
public static class ArticleCodes
{
    /// <summary>
    /// Code article pour les chariots pleins.
    /// </summary>
    public const string Rolls = "ROLLS";

    /// <summary>
    /// Code article pour les chariots vides, explicitement conservé dans le contrat Expédition.
    /// </summary>
    public const string RollsVides = "ROLLS_VIDES";

    /// <summary>
    /// Code article pour les tapis.
    /// </summary>
    public const string Tapis = "TAPIS";

    /// <summary>
    /// Code article pour les sacs.
    /// </summary>
    public const string Sacs = "SACS";
}