// <auto-generated>
// Ce fichier centralise les statuts des brouillons utilisés dans l’application Expédition.
// Les valeurs doivent rester strictement identiques à celles utilisées par l’API centrale.
// </auto-generated>

namespace MobileSLI.Expedition.Web.Domain.Constants;

/// <summary>
/// Statuts possibles pour les brouillons de préparation expédition.
/// </summary>
public static class DraftStatuses
{
    /// <summary>
    /// Le brouillon n'est pas encore préparé.
    /// </summary>
    public const string Brouillon = "BROUILLON";

    /// <summary>
    /// Le brouillon est en préparation côté web.
    /// </summary>
    public const string EnPreparationWeb = "EN_PREPARATION_WEB";

    /// <summary>
    /// Le brouillon est marqué prêt pour verrouillage (masculin).
    /// </summary>
    public const string PretVerrouillage = "PRET_VERROUILLAGE";

    /// <summary>
    /// Le brouillon est marqué prête pour verrouillage (féminin).
    /// </summary>
    public const string PreteVerrouillage = "PRETE_VERROUILLAGE";

    /// <summary>
    /// Le verrouillage est en cours.
    /// </summary>
    public const string VerrouillageEnCours = "VERROUILLAGE_EN_COURS";

    /// <summary>
    /// La tournée est verrouillée.
    /// </summary>
    public const string Verrouille = "VERROUILLE";

    /// <summary>
    /// Le verrouillage a retourné une erreur d'envoi.
    /// </summary>
    public const string ErreurEnvoi = "ERREUR_ENVOI";
}