// <auto-generated>
// Ce fichier centralise les identifiants de fuseaux horaires utilisés dans l'application.
// Utiliser ces constantes évite la répétition de chaînes magiques dans le code.
// </auto-generated>

namespace MobileSLI.Expedition.Web.Domain.Constants;

/// <summary>
/// Fuseaux horaires utilisés par l'application.
/// </summary>
public static class FuseauxHoraires
{
    /// <summary>
    /// Fuseau horaire de Paris (Europe/Paris).
    /// </summary>
    public const string EuropeParis = "Europe/Paris";
}