// <auto-generated>
// Ce fichier centralise les statuts des lots de verrouillage retournés par l’API centrale.
// Les valeurs doivent rester strictement identiques à celles utilisées par l’API centrale.
// </auto-generated>

namespace MobileSLI.Expedition.Web.Domain.Constants;

/// <summary>
/// Statuts possibles pour les lots de verrouillage retournés par l'API centrale.
/// </summary>
public static class LotStatuses
{
    /// <summary>
    /// Lot traité avec succès.
    /// </summary>
    public const string Success = "SUCCESS";

    /// <summary>
    /// Lot déjà traité.
    /// </summary>
    public const string AlreadyProcessed = "ALREADY_PROCESSED";

    /// <summary>
    /// Lot déjà verrouillé.
    /// </summary>
    public const string AlreadyLocked = "ALREADY_LOCKED";

    /// <summary>
    /// Erreur d'envoi du lot.
    /// </summary>
    public const string ErreurEnvoi = "ERREUR_ENVOI";

    /// <summary>
    /// Lot envoyé avec succès.
    /// </summary>
    public const string Envoye = "ENVOYE";

    /// <summary>
    /// Le lot a été rejoué à l'identique.
    /// </summary>
    public const string RejoueIdentique = "REJOUE_IDENTIQUE";

    /// <summary>
    /// Erreur technique lors du traitement du lot.
    /// </summary>
    public const string TechnicalError = "TECHNICAL_ERROR";

    /// <summary>
    /// Erreur de validation lors du traitement du lot.
    /// </summary>
    public const string ValidationError = "VALIDATION_ERROR";

    /// <summary>
    /// Conflit détecté lors du traitement du lot (version anglaise).
    /// </summary>
    public const string Conflict = "CONFLICT";

    /// <summary>
    /// Conflit détecté lors du traitement du lot (version française).
    /// </summary>
    public const string Conflit = "CONFLIT";
}